sabnzbd:
  image: sbrants/sabnzbd
  volumes_from:
    - settings
  restart: always
sickbeard:
  image: sbrants/sickbeard
  links:
    - sabnzbd
  volumes_from:
    - settings
  restart: always
couchpotato:
  image: sbrants/couchpotato
  links:
    - sabnzbd
  volumes_from:
    - settings
  restart: always
ddclient:
  build: ddclient
  restart: always
settings:
  build: settings
plex:
  image: timhaak/plex
  ports:
    - "32400:32400"
  net: "host"
  restart: always
ganglia:
  image: wookietreiber/ganglia
  restart: always
reverseproxy:
  build: reverseproxy
  ports:
    - "443:443"
    - "80:80"
  links:
    - sabnzbd
    - sickbeard
    - couchpotato
    - ganglia
  restart: always
