sabnzbd:
  image: sbrants/sabnzbd
  volumes:
    - /mnt/drobo/Public/Configs/sabnzbd_data:/sabnzbd_data
    - /mnt/drobo/Public/temp_download/complete:/data/complete
    - /mnt/drobo/Public/temp_download/incomplete:/data/incomplete
  restart: always
sonarr:
  image: tuxeh/sonarr
  restart: always
  volumes:
    - /mnt/drobo/Public/Series:/volumes/media
    - /config_sonar/config:/volumes/config
    - /mnt/drobo/Public/temp_download/complete/tv:/volumes/completed
  links:
    - sabnzbd
couchpotato:
  image: sbrants/couchpotato
  links:
    - sabnzbd
  volumes:
    - /mnt/drobo/Public/Configs/couchpotato_data:/couchpotato_data
    - /mnt/drobo/Public/temp_download/complete:/data/complete
    - /mnt/drobo/Public/Movies:/movies
  restart: always
ddclient:
  build: ddclient
  restart: always
plex:
  image: timhaak/plex
  net: "host"
  volumes:
    - /mnt/drobo/Public:/data
    - /PlexConfig:/config
    - /mnt/drobo/Public/PlexBackup:/backup
  restart: always
ganglia:
  image: wookietreiber/ganglia
  command: --without-gmond --timezone US/Pacific
  restart: always
  volumes:
    - /etc/ganglia/:/etc/ganglia/
    - /var/lib/ganglia/:/var/lib/ganglia/
reverseproxy:
  build: reverseproxy
  ports:
    - "443:443"
    - "80:80"
  links:
    - sabnzbd
    #- sickbeard
    - couchpotato
    - ganglia
    - sonarr
  restart: always
