settings:
  build: settings
ddclient:
  build: ddclient
sabnzbd:
  build: sabnzbd
  volumes_from:
    - settings
sickbeard:
  build: sickbeard
  links:
    - sabnzbd
  volumes_from:
    - settings
  restart: always
couchpotato:
  build: couchpotato
  links:
    - sabnzbd
  volumes_from:
    - settings
  restart: always
reverseproxy:
  build: reverseproxy
  ports:
    - "443:443"
  links:
    - sabnzbd
    - sickbeard
    - couchpotato
