sabnzbd:
    #image: sbrants/sabnzbd
    build: sabnzbd
    ports:
        - "8080:8080"
        - "9090:9090"
    volumes:
        - ~/sabnzbd/config:/config
sickbeard:
    #image: sbrants/sickbeard
    build: sickbeard
    ports:
      - "8081:8081"
    volumes:
      - ~/sickbeard/config:/config
    volumes_from:
      - sabnzbd
