settings:
  build: settings
sabnzbd:
  build: sabnzbd
  volumes_from:
    - settings
sickbeard:
  build: sickbeard
  links:
    - sabnzbd
  volumes_from:
    - settings
couchpotato:
  build: couchpotato
  links:
    - sabnzbd
  volumes_from:
    - settings
reverseproxy:
  build: reverseproxy
  ports:
    - "443:443"
  links:
    - sabnzbd
    - sickbeard
    - couchpotato
