ddclient:
  image: sbrants/ddclient
sabnzbd:
  image: sbrants/sabnzbd
  volumes_from:
    - settings
sickbeard:
  image: sbrants/sickbeard
  links:
    - sabnzbd
  volumes_from:
    - settings
  restart: always
couchpotato:
  image: sbrants/couchpotato
  links:
    - sabnzbd
  volumes_from:
    - settings
  restart: always
settings:
  build: settings
reverseproxy:
  build: reverseproxy
  ports:
    - "443:443"
  links:
    - sabnzbd
    - sickbeard
    - couchpotato
